export const mockBillData = {
  company: {
    name: 'Best Clinic 24',
    vatNumber: '123456789',
    address: '123 Medical St., Tel Aviv',
    phone: '+972-3-1234567',
    logoUrl:
      'https://graphicdesignbylisa.com/wp-content/uploads/generic-logo.jpg',
  },
  customer: {
    name: 'John Doe',
    vatNumber: '987654321',
  },
  invoice: {
    note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti dolorum perspiciatis quidem delectus reprehenderit, possimus aspernatur repellendus, qui distinctio, quae itaque quis libero rem fuga dolore ut placeat quam odit.',
    referenceNumber: 'INV-2025-001',
    confirmationNumber: '987891699',
    date: '2025-06-19',
    type: 'TAX INVOICE',
    printType: 'Copy',
  },
  items: [
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
    {
      catalogCode: 'MED001',
      name: 'X-Ray Service',
      description: 'Standard chest X-ray',
      measureUnit: 'unit',
      quantity: 1,
      price: 200,
      discount: 20,
      vatRate: 17,
      vatAmount: 30.6,
      fullTotal: 210.6,
    },
    {
      catalogCode: 'MED002',
      name: 'Blood Test',
      description: 'Full panel',
      measureUnit: 'unit',
      quantity: 1,
      price: 300,
      discount: 30,
      vatRate: 17,
      vatAmount: 45.9,
      fullTotal: 315.9,
    },
  ],
  summary: {
    total: 500,
    itemsDiscount: 50,
    generalDiscount: 0,
    totalAfterDiscount: 450,
    tax: 76.5,
    fullTotal: 526.5,
  },
};
